### PR TITLE
1.5.1 lgg fork and Repo & /GameData restructure

### PR DESCRIPTION
**Pull request by StoneBlue**
Folder restructure

- Removed old /Parts folder from master
- Added /GameData folder (full release version)
- Converted/resized .mbm to .dds
- Cleaned up .cfg file formatting
- Moved .dll location to /Plugins folder
- Forked from LGG fork (contains his Source files for the 1.5.1 recompile)
- Added copies of new LICENSE/README files from Ezriilc repo)

### CODE REVIEW

**Comment by Ezriilc** [comment]
Excellent!  Thank you - I really appreciate it.  I assume you've built and tested this.

**Comment by StoneBlue** [comment]
Also, a note, that it seems the textures were converted to .dds quite awhile ago, and have *never* made it into *any* subsequent release package. *ALL* of the release .zips still have .mbm textures, not .dds, as in the /Parts folder in the master repo.

I've added them in the /GameData folder in the master, as well as adding a copy of LGG's v0.4.4 compiled .dll to the /Plugins folder.
Thus, the whole /GameData folder as-is, is basically a complete release, and can be zipped up and provided as a complete v0.4.4 package, compatable with KSP 1.5.1+ (most likely, at least up to 1.7.3).
That can be provided as a replacement of the vBETA-1 "patch" zip, that ONLY contains the .dll.
Hopefully the /GameData in the master, can serve as a template for release packages going forward, for who ever can do future recompiles.
The mod *should* really get a recompile against .NET 4.5 (or greater), and going forward, as pretty much required by the KSP 1.8.0 update.

**Comment by StoneBlue** [comment]
Actually, it depends... :P 
I made the folder/texture/cfg edits, and tested with LGGs 1.5.1 compiled .dll.
Works as expected... (at least nothing *I* changed caused issues).

I spent a couple days trying to recompile it myself for 1.8.1, and had mixed results.
I'm not a coder by any means, but i did get a decently clean compile, with no errors, and only a few warnings. I did test it, and no exceptions or nullrefs in the log. Actually, there was NOTHING in the KSP.log complaining about my .dll.

HOWEVER, I'm not sure if my .dll completely *works* in-game. I did not include ANYTHING I tried with the Source files in my PR. I kept those out, strictly on my local fork. I'm just not 100% confident my compile was done the correct way. If someone wants to hit me up for my modified source files, or attempt to use my .dll for *testing* only, feel free to hit me up and I will share.

**Comment by Ezriilc** [comment]
Fair enough.  I'll give it a go.

**Comment by StoneBlue** [comment]
Kewl.. lmk if there are any issues, *other* than coding issues with the .dll :P 
To reiterate:
GameData is all me (also deleted the /Parts folder from the repo. New one included in /GameData)
Source and all other files are direct from LGGs 1.5.1 fork
LICENSE.txt & README.md is what you just added a couple days ago

**Comment by Ezriilc** [comment]
I've done a quick test and the only issue I see is a lack of a toolbar button, which I thought was included (I may be wrong, or just not doing it right; it has been a while since I've played KSP).

Other than that, all seems to be working as I remember, even the .CSV and .PNG output!  Great work!

If we're all satisfied with it (I am), then perhaps I should publish a full release?

**Comment by Ezriilc** [comment]
I've changed the .csproj file to my own KSP game location, but when I try to build, it throws a whole mess of errors.  I think they're related to missing references, but I just don't know enough to know what to do about them.  I wanted to update the .dll with the new version, but I'm stuck.  I suppose I can just not worry about it and publish.

> Error	CS0234	The type or namespace name 'Reflection' does not exist in the namespace 'System' (are you missing an assembly reference?)	Graphotron	D:\MyDocs2\GitHub\KSP-Graphotron\Source\AssemblyInfo.cs	1	Active
> Error	CS0246	The type or namespace name 'AssemblyTitleAttribute' could not be found (are you missing a using directive or an assembly reference?)	Graphotron	D:\MyDocs2\GitHub\KSP-Graphotron\Source\AssemblyInfo.cs	6	Active
> Error	CS0246	The type or namespace name 'AssemblyTitle' could not be found (are you missing a using directive or an assembly reference?)	Graphotron	D:\MyDocs2\GitHub\KSP-Graphotron\Source\AssemblyInfo.cs	6	Active
> Error	CS0518	Predefined type 'System.String' is not defined or imported	Graphotron	D:\MyDocs2\GitHub\KSP-Graphotron\Source\AssemblyInfo.cs	6	Active

**Comment by StoneBlue** [comment]
Hmmm... actually, did you try the existing .dll in the /GameData I added? That is just a copy of the exact .dll file that's in the BETA-1.zip file on the website. That was compiled by LGG, wasnt it? vOv 
You (or anyone wanting to try the mod as a "drop-in" release), can just copy/paste the contents of the /GameData right from the repo, into the KSP install.
Coulda swore that had a working Toolbar button?... or was that *my* compile?... now I forgot... :P 
I'll check.

**Comment by Ezriilc** [comment]
Yep, and it works well.  I hadn't realized it was just the BETA that I've already got up, and yeah, I think it was from LGG.  I didn't see any toolbar button in my test.  If you've been able to do a build with framework 4.5, I'd love to know what your settings were/are, then I could maybe do a full release.

**Comment by StoneBlue** [comment]
Ugh... Just checked, and, uh... yeah, it *was* my build where the toolbar button started working... :face_palm:

**Comment by Ezriilc** [comment]
Well, that's great!  Imma try and build it.

**Pull request merged**
